import { createSlice } from "@reduxjs/toolkit";

export const languageSlice = createSlice({
  name: "language",
  initialState: {
    words: {
      en: {
        set_language: "Français",
        sample: "SAMPLE",
        clear_all: "CLEAR ALL",
        pdf: "PDF",
        live_edit: "LIVE EDIT",
        import: "IMPORT",
        export: "EXPORT",
        primary: "Primary",
        secondary: "Secondary",
        title: "Main Title",
        subtitle: "Subtitle",
        titles: "Titles",
        textLeft: "Text 1",
        textRight: "Text 2",
        color_hint: "* double click the color for the default color",
        add: "ADD",
        clear: "CLEAR",
        personal_information: "Personal Information",
        social: "Social",
        languages: "Languages",
        hobbies: "Hobbies",
        education: "Education",
        experience: "Experience",
        skills: "Skills",
        projects: "Projects",
        courses: "Courses",
        references: "References",
        social_upper: "SOCIAL",
        languages_upper: "LANGUAGES",
        hobbies_upper: "HOBBIES",
        education_upper: "EDUCATION",
        experience_upper: "EXPERIENCE",
        skills_upper: "SKILLS",
        projects_upper: "PROJECTS",
        courses_upper: "COURSES",
        references_upper: "REFERENCES",
        name_surname: "Name Surname",
        form_title: "Title",
        photo: "Photo",
        address: "Address",
        phone_number: "Phone Number",
        email_address: "Email Address",
        about: "About",
        twitter_username: "Twitter Username",
        github_username: "Github Username",
        linkedin_username: "LinkedIn Username",
        personal_website: "Personal Website",
        external_url: "External URL",
        username_or_url: "Username or URL Address",
        select: "Select",
        language: "Language Name",
        native: "Native Language",
        hobby: "Hobby Name",
        school: "School Name",
        subject: "Subject",
        degree: "Degree",
        city: "City",
        from: "From",
        to: "To",
        company: "Company Name",
        position: "Position",
        description: "Description",
        skill: "Skill Name",
        level: "Level",
        project: "Project Name",
        link: "Project Link",
        course: "Course Name",
        reference: "Reference Name",
        reference_title: "Reference Title",
        confirm: "Are you sure all data will be deleted?",
        top: "Top",
        right: "Right",
        bottom: "Bottom",
        left: "Left",
        margin_hint: "* you can set print page margins",
      },
      tr: {
        set_language: "ENGLISH",
        sample: "Exemple",
        clear_all: "SUPPRIMER TOUT",
        pdf: "PDF",
        live_edit: "Edition en direct",
        import: "Importer",
        export: "Exporter",
        primary: "Primaire",
        secondary: "Secondaire",
        title: "Titre",
        subtitle: "Sous titre",
        titles: "Titres",
        textLeft: "Article 1",
        textRight: "Article 2",
        color_hint: "*Double-clique sur la couleur pour revenir à la couleur par défaut",
        add: "Ajouter",
        clear: "Supprimer",
        personal_information: "Informations Personnelles",
        social: "Social",
        languages: "Langues",
        hobbies: "Loisirs",
        education: "Education",
        experience: "Experience",
        skills: "Capacités",
        projects: "Projets",
        courses: "Cours",
        references: "Les références",
        social_upper: "SOCIAL",
        languages_upper: "LANGUES",
        hobbies_upper: "LOISIRS",
        education_upper: "ÉDUCATION",
        experience_upper: "EXPÉRIENCE",
        skills_upper: "COMPÉTENCES",
        projects_upper: "PROJETS",
        courses_upper: "COURS",
        references_upper: "LES RÉFÉRENCES",
        name_surname: "Prénom / nom de famille",
        form_title: "Titre",
        photo: "Photo",
        address: "Adresse",
        phone_number: "Numéro de téléphone",
        email_address: "Adresse e-mail",
        about: "À propos",
        twitter_username: "Nom d'utilisateur Twitter",
        github_username: "Nom d'utilisateur Github",
        linkedin_username: "Nom d'utilisateur LinkedIn",
        personal_website: "Site Web personnel",
        external_url: "lien externe",
        username_or_url: "Nom d'utilisateur ou lien",
        select: "Choisir",
        language: "Nom de la langue",
        native: "Langue maternelle",
        hobby: "Nom du passe-temps",
        school: "Nom de l'école",
        subject: "Section",
        degree: "Diplôme",
        city: "Ville",
        from: "Date de début",
        to: "Date de fin",
        company: "Nom de l'entreprise",
        position: "Position",
        description: "Définition",
        skill: "Nom du talent",
        level: "Niveau",
        project: "Nom du projet",
        link: "Lien du projet",
        course: "Nom du cours",
        reference: "Nom de référence",
        reference_title: "Titre de référence",
        confirm: "Êtes-vous sûr que toutes les données seront supprimées ?",
        top: "Haut",
        right: "Droite",
        bottom: "Inférieur",
        left: "Gauche",
        margin_hint: "* vous pouvez ajuster les marges de la page d'impression",
      },
    },
    language: "en",
  },
  reducers: {
    setLanguage: (state, action) => {
      state.language = action.payload;
    },
  },
});

export const { setLanguage } = languageSlice.actions;

export default languageSlice.reducer;
